### PR TITLE
switch to golang.org/x/sys

### PR DESCRIPTION
**Pull request by Stebalien**
syscall is frozen and mostly deprecated.

### CODE REVIEW

**Comment by magik6k** [comment]
We probably want to use gx-ified sys -> https://github.com/gxed/badger/blob/master/package.json#L29 (I can't find GH repo for that on gxed, cc @Kubuxu @whyrusleeping)

**Comment by whyrusleeping** [comment]
Yeah, we currently have multiple different golang.org/x/sys gx imports going on. `gx deps | grep sys`. @Stebalien lets use the one in badger (because i think its the most recent)

**Comment by whyrusleeping** [comment]
we might even want to update to the latest code there throughout our entire codebase.

**Comment by Stebalien** [comment]
@whyrusleeping donw with switching to gxed. We'll still need to update badger (couldn't get the hashes to match...).

**Pull request merged**
