### PR TITLE
Add basic .travis.yml file.

### PR DESCRIPTION
**Pull request by kevina**

### CODE REVIEW

**Comment by kevina** [comment]
Note: This needs to be enables on Travis CI:  https://travis-ci.org/libp2p/go-sockaddr

**Comment by Stebalien** [comment]
Travis is now enabled.

**Comment by kevina** [comment]
Just FYI: this repo does not use gx, but fixing that (if necessary) can be done in a separate p.r.

**Comment by Stebalien** [comment]
@kevina It does. You're copy is probably out of date.

**Comment by kevina** [comment]
@Stebalien there is nothing gx related in the Makefile, https://github.com/libp2p/go-sockaddr/blob/master/Makefile

**Comment by Stebalien** [comment]
Ah. Yes, the project uses gx (there's a package.json) but the makefile doesn't (yet). I'd just fix that now.

**Pull request merged**
